// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// FreshCoffee_List ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IFreshCoffee_ListViewModel
    {		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        Visibility IsInternetAvalaible { get; }
        /// <summary>
        /// Gets/Sets the FreshCoffee_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.FreshCoffeeSchema> FreshCoffee_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the FreshCoffee_ListListControlCollectionPageNumber property.
        /// </summary>
		int FreshCoffee_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedFreshCoffee_ListListControlCollection property.
        /// </summary>
		Entities.FreshCoffeeSchema SelectedFreshCoffee_ListListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the GetFreshCoffee_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetFreshCoffee_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
