// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// FreshCoffee_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IFreshCoffee_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentFreshCoffeeSchema property.
        /// </summary>
		Entities.FreshCoffeeSchema CurrentFreshCoffeeSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaFreshCoffee_Detail0 property.
        /// </summary>
		bool HasNextpanoramaFreshCoffee_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaFreshCoffee_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaFreshCoffee_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechFreshCoffee_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechFreshCoffee_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareFreshCoffee_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareFreshCoffee_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartFreshCoffee_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartFreshCoffee_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaFreshCoffee_Detail0 command.
        /// </summary>
		ICommand NextpanoramaFreshCoffee_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaFreshCoffee_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaFreshCoffee_Detail0 { get; }

	}
}
