// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// FreshCoffee_FreshCoffee interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IFreshCoffee_FreshCoffee
    {
		ObservableCollection<Entities.FreshCoffeeSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.FreshCoffeeSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.FreshCoffeeSchema current);
		bool HasNext(Entities.FreshCoffeeSchema current);
		Entities.FreshCoffeeSchema Previous(Entities.FreshCoffeeSchema current);
		Entities.FreshCoffeeSchema Next(Entities.FreshCoffeeSchema current);
    }
}
